name: Build & Publish NPM Packages

on:
  push:
    branches:
      - next-version

env:
  NODE_VERSION: '21'

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/next-version/
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          type: ''
          pattern: 'dpi_v(.*)'
          group-index: 1
          from: 'tags'