name: Build & Publish NPM Packages

on:
  push:
    branches:
      - next-version

env:
  NODE_VERSION: '21'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        id: hello
        uses: longht021189/npm-collection/next-version@7ae9a8bac3c06e10bf7295efd8f4214ec137e299
        with:
          who-to-greet: 'Mona the Octocat'

      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
